import type { TabConfig } from '../types'
import { NEWS_CATEGORIES } from '../../types/news'

export const TABS: TabConfig[] = [
  // ── Startseite ──────────────────────────────────────────────────────────
  {
    key: 'startseite',
    label: 'Startseite',
    file: '/data/startseite.json',
    ghPath: 'public/data/startseite.json',
    type: 'object',
    topFields: [
      {
        key: 'heroSlogan',
        label: 'Hero-Slogan',
        type: 'textarea',
        placeholder: 'Gemeinsam für Albstadt — sozial, gerecht und zukunftsorientiert.',
      },
      {
        key: 'heroBadge',
        label: 'Badge-Text (kleiner Text über dem Titel)',
        type: 'text',
        placeholder: 'Ortsverein Albstadt · Zollernalb',
      },
    ],
  },
  {
    key: 'news',
    label: 'Aktuelles',
    file: '/data/news.json',
    ghPath: 'public/data/news.json',
    type: 'array',
    previewPath: '/#aktuelles',
    fields: [
      { key: 'datum', label: 'Datum', type: 'date', required: true },
      { key: 'titel', label: 'Titel', type: 'text', required: true },
      { key: 'zusammenfassung', label: 'Zusammenfassung', type: 'textarea' },
      { key: 'inhalt', label: 'Inhalt', type: 'textarea' },
      {
        key: 'kategorie',
        label: 'Kategorie',
        type: 'select',
        options: [...NEWS_CATEGORIES],
      },
      { key: 'bildUrl', label: 'Titelbild', type: 'image', imageDir: 'news' },
      { key: 'bildBeschreibung', label: 'Bildunterschrift Titelbild', type: 'text' },
      {
        key: 'bildUrls',
        label: 'Weitere Bilder',
        type: 'imagelist',
        imageDir: 'news',
        captionsKey: 'bildBeschreibungen',
      },
    ],
  },
  {
    key: 'party',
    label: 'Partei',
    file: '/data/party.json',
    ghPath: 'public/data/party.json',
    type: 'object',
    previewPath: '/#partei',
    topFields: [{ key: 'beschreibung', label: 'Beschreibung', type: 'textarea' }],
    sections: [
      {
        key: 'schwerpunkte',
        label: 'Schwerpunkte',
        fields: [
          { key: 'titel', label: 'Titel', type: 'text', required: true },
          { key: 'beschreibung', label: 'Kurzbeschreibung (Karte)', type: 'textarea' },
          { key: 'inhalt', label: 'Ausführlicher Text (Detail-Ansicht)', type: 'textarea' },
          { key: 'icon', label: 'Icon', type: 'icon-picker' },
        ],
      },
      {
        key: 'vorstand',
        label: 'Vorstand',
        fields: [
          { key: 'name', label: 'Name', type: 'text', required: true },
          { key: 'rolle', label: 'Rolle / Amt', type: 'text' },
          { key: 'email', label: 'E-Mail', type: 'email' },
          { key: 'phone', label: 'Telefon', type: 'text' },
          { key: 'address', label: 'Adresse', type: 'text' },
          { key: 'place', label: 'PLZ & Ort', type: 'text' },
          { key: 'bildUrl', label: 'Profilbild', type: 'image', imageDir: 'vorstand' },
          { key: 'bio', label: 'Biografie', type: 'textarea' },
        ],
      },
      {
        key: 'abgeordnete',
        label: 'Abgeordnete',
        fields: [
          { key: 'name', label: 'Name', type: 'text', required: true },
          { key: 'rolle', label: 'Rolle', type: 'text' },
          { key: 'wahlkreis', label: 'Wahlkreis', type: 'text' },
          { key: 'email', label: 'E-Mail', type: 'email' },
          { key: 'website', label: 'Website', type: 'url' },
          { key: 'bildUrl', label: 'Profilbild', type: 'image', imageDir: 'abgeordnete' },
          { key: 'bio', label: 'Biografie', type: 'textarea' },
        ],
      },
    ],
  },
  {
    key: 'fraktion',
    label: 'Fraktion',
    file: '/data/fraktion.json',
    ghPath: 'public/data/fraktion.json',
    type: 'object',
    previewPath: '/#fraktion',
    topFields: [{ key: 'beschreibung', label: 'Beschreibung', type: 'textarea' }],
    sections: [
      {
        key: 'gemeinderaete',
        label: 'Gemeinderäte',
        fields: [
          { key: 'name', label: 'Name', type: 'text', required: true },
          { key: 'beruf', label: 'Beruf', type: 'text' },
          { key: 'bildUrl', label: 'Bild', type: 'image', imageDir: 'gemeinderaete' },
          { key: 'seit', label: 'Im Rat seit', type: 'text' },
          { key: 'address', label: 'Adresse', type: 'text' },
          { key: 'zipCode', label: 'PLZ & Ort', type: 'text' },
          { key: 'email', label: 'E-Mail', type: 'email' },
          { key: 'ausschuesse', label: 'Ausschüsse', type: 'stringlist' },
          { key: 'bio', label: 'Biografie', type: 'textarea' },
        ],
      },
      {
        key: 'kreisraete',
        label: 'Kreisräte',
        fields: [
          { key: 'name', label: 'Name', type: 'text', required: true },
          { key: 'beruf', label: 'Beruf', type: 'text' },
          { key: 'bildUrl', label: 'Bild', type: 'image', imageDir: 'kreisraete' },
          { key: 'seit', label: 'Im Rat seit', type: 'text' },
          { key: 'address', label: 'Adresse', type: 'text' },
          { key: 'zipCode', label: 'PLZ & Ort', type: 'text' },
          { key: 'email', label: 'E-Mail', type: 'email' },
          { key: 'ausschuesse', label: 'Ausschüsse', type: 'stringlist' },
          { key: 'bio', label: 'Biografie', type: 'textarea' },
        ],
      },
    ],
  },
  {
    key: 'kommunalpolitik',
    label: 'Kommunalpolitik',
    file: '/data/kommunalpolitik.json',
    ghPath: 'public/data/kommunalpolitik.json',
    type: 'kommunalpolitik',
    previewPath: '/kommunalpolitik',
  },
  {
    key: 'haushaltsreden',
    label: 'Haushaltsreden',
    type: 'haushaltsreden',
    file: null,
    ghPath: null,
  },
  {
    key: 'history',
    label: 'Historie',
    file: '/data/history.json',
    ghPath: 'public/data/history.json',
    type: 'object',
    previewPath: '/#historie',
    topFields: [{ key: 'einleitung', label: 'Einleitung', type: 'textarea' }],
    sections: [
      {
        key: 'timeline',
        label: 'Chronik',
        fields: [
          { key: 'jahr', label: 'Jahr(e)', type: 'text', required: true },
          { key: 'titel', label: 'Titel', type: 'text', required: true },
          { key: 'beschreibung', label: 'Beschreibung', type: 'textarea' },
          {
            key: 'bilder',
            label: 'Bilder',
            type: 'imagelist',
            imageDir: 'historie',
            captionsKey: 'bilderBeschreibungen',
          },
        ],
      },
      {
        key: 'persoenlichkeiten',
        label: 'Kommunale Persönlichkeiten',
        fields: [
          { key: 'name', label: 'Name', type: 'text', required: true },
          { key: 'jahre', label: 'Jahre', type: 'text' },
          { key: 'rolle', label: 'Rolle', type: 'text' },
          { key: 'beschreibung', label: 'Beschreibung', type: 'textarea' },
          { key: 'bildUrl', label: 'Profilbild', type: 'image', imageDir: 'persoenlichkeiten' },
          {
            key: 'bildUrls',
            label: 'Weitere Bilder',
            type: 'imagelist',
            imageDir: 'persoenlichkeiten',
          },
        ],
      },
    ],
  },
  {
    key: 'impressum',
    label: 'Impressum',
    file: '/data/impressum.json',
    ghPath: 'public/data/impressum.json',
    type: 'object',
    previewPath: '/impressum',
    topFields: [
      {
        key: 'beschreibung',
        label: 'Beschreibung (Unterzeile im Header)',
        type: 'textarea',
        placeholder: 'Angaben gemäß § 5 TMG sowie weitere rechtliche Hinweise.',
      },
    ],
    sections: [
      {
        key: 'sections',
        label: 'Abschnitte',
        fields: [
          { key: 'title', label: 'Überschrift', type: 'text', required: true },
          { key: 'content', label: 'Inhalt', type: 'textarea' },
        ],
      },
    ],
  },
  {
    key: 'datenschutz',
    label: 'Datenschutz',
    file: '/data/datenschutz.json',
    ghPath: 'public/data/datenschutz.json',
    type: 'object',
    previewPath: '/datenschutz',
    topFields: [
      {
        key: 'beschreibung',
        label: 'Beschreibung (Unterzeile im Header)',
        type: 'textarea',
        placeholder: 'Informationen zum Umgang mit Ihren personenbezogenen Daten gemäß DSGVO.',
      },
    ],
    sections: [
      {
        key: 'sections',
        label: 'Abschnitte',
        fields: [
          { key: 'title', label: 'Überschrift', type: 'text', required: true },
          { key: 'content', label: 'Inhalt', type: 'textarea' },
        ],
      },
    ],
  },
  // ── Kontakt ─────────────────────────────────────────────────────────────
  {
    key: 'kontakt',
    label: 'Kontakt',
    file: '/data/kontakt.json',
    ghPath: 'public/data/kontakt.json',
    type: 'object',
    previewPath: '/#kontakt',
    topFields: [
      { key: 'adresse', label: 'Anschrift (Zeilenumbrüche mit Enter)', type: 'textarea' },
      { key: 'email', label: 'E-Mail-Adresse', type: 'email', iconKey: 'mail' },
      { key: 'telefon', label: 'Telefon', type: 'text', iconKey: 'phone' },
      {
        key: 'formspreeUrl',
        label: 'Formspree-URL (Kontaktformular)',
        type: 'url',
        iconKey: 'link',
      },
      { key: 'gruppenbild', label: 'Gruppenbild', type: 'image', imageDir: 'kontakt' },
      {
        key: 'footerBeschreibung',
        label: 'Footer-Beschreibungstext',
        type: 'textarea',
        placeholder: 'Sozialdemokratische Partei Deutschlands, Ortsverein Albstadt…',
      },
      {
        key: 'facebookUrl',
        label: 'Facebook-URL',
        type: 'url',
        iconKey: 'facebook',
        placeholder: 'https://facebook.com/…',
      },
      {
        key: 'instagramUrl',
        label: 'Instagram-URL',
        type: 'url',
        iconKey: 'instagram',
        placeholder: 'https://instagram.com/…',
      },
    ],
    sections: [
      {
        key: 'buerozeiten',
        label: 'Bürozeiten',
        fields: [
          { key: 'tage', label: 'Tage', type: 'text', required: true },
          { key: 'zeit', label: 'Zeit', type: 'text', required: true },
        ],
      },
    ],
  },
  // ── Einstellungen (technische App-Einstellungen) ─────────────────────────
  {
    key: 'config',
    label: 'Einstellungen',
    file: '/data/config.json',
    ghPath: 'public/data/config.json',
    type: 'object',
    topFields: [
      {
        key: 'icsUrl',
        label: 'Kalender-URL (ICS)',
        type: 'url',
        iconKey: 'calendar',
        placeholder: 'https://…/kalender.ics',
      },
      {
        key: 'elfsightAppId',
        label: 'Elfsight App-ID (Instagram-Feed)',
        type: 'text',
        iconKey: 'instagram',
        placeholder: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
      },
    ],
  },
]
